---
- name: Create sites-available directory
  ansible.builtin.file:
    path: /etc/nginx/sites-available
    state: directory
    owner: root
    group: root
    mode: "0755"
- name: Create sites-enabled directory
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled
    state: directory
    owner: root
    group: root
    mode: "0755"
- name: Configure virtual hosts
  ansible.builtin.template:
    src: vhost.conf.j2
    dest: /etc/nginx/sites-available/{{ item.key }}.conf
    owner: root
    group: root
    mode: "0644"
  loop: "{{ nginx_sites | dict2items }}"
  notify: Reload nginx
- name: Enable virtual hosts
  ansible.builtin.file:
    src: /etc/nginx/sites-available/{{ item.key }}.conf
    dest: /etc/nginx/sites-enabled/{{ item.key }}.conf
    state: link
    owner: root
    group: root
  loop: "{{ nginx_sites | dict2items }}"
  notify: Reload nginx
